import { OnInit, ElementRef } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { Overlay } from '@angular/cdk/overlay';
import { SearchSelectService } from './search-select.service';
export declare class SearchSelectComponent implements OnInit, ControlValueAccessor {
    private httpClient;
    elementRef: ElementRef;
    overlay: Overlay;
    searchSelectService: SearchSelectService;
    inputcomponent: any;
    configs: any;
    readonly: boolean;
    private desconto;
    listEnabled: boolean;
    searchString: string;
    semResultados: boolean;
    keyupDelay: any;
    mainArray: any[];
    disableScrollDetect: boolean;
    onChange: (_: any) => void;
    value: any;
    onTouched: () => void;
    constructor(httpClient: HttpClient, elementRef: ElementRef, overlay: Overlay, searchSelectService: SearchSelectService);
    defaultValue: string;
    writeValue(obj?: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    propagateChange: (_: any) => void;
    onClearClick(): void;
    setDefault(): void;
    onTypeSearchInput(): void;
    overlayRef: any;
    compRef: any;
    toggleSelect(act: any): void;
    inputFocusFunction(ev: any): void;
    onGlobalClick(event: any): void;
    ngOnInit(): void;
    ngOnDestroy(): void;
}
